# Generated by Django 5.2.8 on 2025-11-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='필수값. 이메일이 로그인 필드입니다.', max_length=150, verbose_name='사용자명'),
        ),
    ]
