# Generated by Django 5.2.8 on 2025-11-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='대화 제목')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='시작일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최종 업데이트')),
            ],
            options={
                'verbose_name': '대화 세션',
                'verbose_name_plural': '대화 세션',
                'db_table': 'conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '사용자'), ('assistant', '챗봇')], max_length=10, verbose_name='역할')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('thinking_process', models.JSONField(blank=True, help_text='랭그래프 노드 진행 과정: [{"node": "classify", "description": "질문 분류 중...", "order": 1}, ...]', null=True, verbose_name='사고 과정')),
            ],
            options={
                'verbose_name': '메시지',
                'verbose_name_plural': '메시지',
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
    ]
