# Generated by Django 5.2.8 on 2025-11-14 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='대화 제목')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='시작일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최종 업데이트')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '대화 세션',
                'verbose_name_plural': '대화 세션',
                'db_table': 'conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '사용자'), ('assistant', '챗봇')], max_length=10, verbose_name='역할')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('thinking_process', models.JSONField(blank=True, help_text='랭그래프 노드 진행 과정: [{"node": "classify", "description": "질문 분류 중...", "order": 1}, ...]', null=True, verbose_name='사고 과정')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.conversation', verbose_name='대화 세션')),
            ],
            options={
                'verbose_name': '메시지',
                'verbose_name_plural': '메시지',
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiseaseQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100, verbose_name='질환명')),
                ('searched_at', models.DateTimeField(auto_now_add=True, verbose_name='검색 시간')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_queries', to='chatbot.message', verbose_name='메시지')),
            ],
            options={
                'verbose_name': '질환 검색',
                'verbose_name_plural': '질환 검색들',
                'db_table': 'disease_query',
                'ordering': ['-searched_at'],
            },
        ),
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment_type', models.CharField(choices=[('positive', '긍정'), ('negative', '부정'), ('neutral', '중립')], max_length=20, verbose_name='감정 타입')),
                ('sentiment_score', models.FloatField(verbose_name='감정 점수')),
                ('keywords', models.JSONField(default=list, verbose_name='감정 키워드')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, verbose_name='분석 시간')),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sentiment', to='chatbot.message', verbose_name='메시지')),
            ],
            options={
                'verbose_name': '감정 분석',
                'verbose_name_plural': '감정 분석들',
                'db_table': 'sentiment_analysis',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['updated_at'], name='conversatio_updated_8d1310_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['user', 'updated_at'], name='conversatio_user_id_41671b_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='messages_convers_3ebb41_idx'),
        ),
        migrations.AddIndex(
            model_name='diseasequery',
            index=models.Index(fields=['disease_name', '-searched_at'], name='disease_que_disease_5396f7_idx'),
        ),
    ]
